-- New notification

INSERT OR REPLACE INTO "LocalizedText"
	(	"Language",	"Tag",											"Text"																				)
VALUES
	(	'en_US',	'LOC_NOTIFICATION_INJECT_FREE_CITY_MESSAGE',	'New Free City!'																	),
	(	'en_US',	'LOC_NOTIFICATION_INJECT_FREE_CITY_SUMMARY',	'The Barbarians of the {1_TribeName} have formed the Free City of {2_CityName}.'	);

-- In-game text update

INSERT OR REPLACE INTO LocalizedText
	(	"Language",	"Tag",															"Text"																																																																																																																																																																																									)
VALUES
	(	'en_US',	'LOC_UNITCOMMAND_TREAT_WITH_CLAN_RAID_HELP',					'Earn {1_GoldAmount} [ICON_GOLD] Gold. The Outpost will remain intact and lose {2_ProgressAmount} points towards Free City conversion. Clans can be raided once every {3_Turns} turns.'																																																																																																																																													),
	(	'en_US',	'LOC_UNITCOMMAND_TREAT_WITH_CLAN_HIRE_HELP',					'Spend {1_GoldAmount} [ICON_Gold] Gold to hire a {4_UnitName} unit from this clan. The unit will appear near the city of {5_CityName} this turn. The clan will gain {2_ProgressAmount} points towards Free City conversion. Clans can be hired once every {3_Turns} turns.'																																																																																																																								),
	(	'en_US',	'LOC_UNITCOMMAND_TREAT_WITH_CLAN_RANSOM_HELP',					'Spend {1_GoldAmount} [ICON_Gold] Gold to recover your captured {2_UnitName}. The clan will lose progress towards Free City conversion.'																																																																																																																																																								),
	(	'en_US',	'LOC_UNITCOMMAND_TREAT_WITH_CLAN_BRIBE_HELP',					'Spend {1_GoldAmount} [ICON_Gold] Gold to prevent this clan from attacking your cities for {2_Turns} turns. The clan will gain {3_ProgressAmount} points towards Free City conversion.'																																																																																																																																													),
	(	'en_US',	'LOC_UNITCOMMAND_TREAT_WITH_CLAN_INCITE_HELP',					'Spend {1_GoldAmount} [ICON_Gold] Gold to encourage this clan to attack {4_CivName}. The clan will lose {2_ProgressAmount} points towards Free City conversion. Clans can be incited once every {3_Turns} turns.'																																																																																																																																						),
	(	'en_US',	'LOC_UNITCOMMAND_TREAT_WITH_CLAN_INCITE_HELP_GENERIC',			'Spend [ICON_Gold] Gold to encourage this clan to attack another nearby civilization or City-State. The clan will lose {1_ProgressAmount} points towards Free City conversion. Clans can be incited once every {2_Turns} turns.'																																																																																																																																		),
	(	'en_US',	'LOC_TRIBE_BANNER_CONVERSION_TIP_TURNS',						'Free City Conversion: {1_Turns}+ Turns'																																																																																																																																																																																),
	(	'en_US',	'LOC_TRIBE_BANNER_CONVERSION_TIP_IMMINENT',						'Free City Conversion: Imminent'																																																																																																																																																																																		),
	(	'en_US',	'LOC_TRIBE_BANNER_CONVERSION_TIP_DISABLED',						'Free City Conversion Disabled'																																																																																																																																																																																			),
	(	'en_US',	'LOC_TRIBE_BANNER_CONVERSION_TIP_DISABLED_NO_CANDIDATES',		'Free City Conversion Disabled: No City-States available'																																																																																																																																																																												),
	(	'en_US',	'LOC_TRIBE_BANNER_CONVERSION_TIP_DISABLED_INVALID_LOCATION',	'Free City Conversion Disabled: Too close to existing cities'																																																																																																																																																																											),
	(	'en_US',	'LOC_PEDIA_CONCEPTS_PAGE_CLANS_CHAPTER_CITYCONVERSION_TITLE',	'Clan Conversions to Free Cities'																																																																																																																																																																																		),
	(	'en_US',	'LOC_PEDIA_CONCEPTS_PAGE_CLANS_CHAPTER_CITYCONVERSION_PARA_1',	'In this mode, clans that successfully remain in play long enough can convert into Free Cities.'																																																																																																																																																																		),
	(	'en_US',	'LOC_PEDIA_CONCEPTS_PAGE_CLANS_CHAPTER_CITYCONVERSION_PARA_3',	'When a Barbarian Clan converts into a Free City, their Outpost is immediately replaced by the new city under its new name.'																																																																																																																																																											),
	(	'en_US',	'LOC_PEDIA_CONCEPTS_PAGE_CLANS_CHAPTER_UNITCOMMANDS_PARA_2',	'Raiding an Outpost rewards [ICON_GOLD] Gold to the player and reduces the clan''s progress towards Free City conversion, but does not destroy the Outpost. When a clan is raided, it gains immunity to raids for a short duration. Raided clans will also spawn a defender unit in reprisal the same turn they are raided, ejecting any foreign unit in their Outpost in the process.'																																																																																													),
	(	'en_US',	'LOC_PEDIA_CONCEPTS_PAGE_CLANS_CHAPTER_PLAYEROPS_PARA_2',		'HIRING a clan: spend [ICON_GOLD] Gold to purchase a military unit from the clan. The unit provided will be the best the clan can currently train -- it could even be a Unique Unit!  Unlike levying a City-State, hired units are permanently under your control. They appear the same turn on a plot near to your closest city. Clans that are hired cannot be hired again for a short duration. Hiring a clan increases their Free City conversion progress.'																																																																										),
	(	'en_US',	'LOC_PEDIA_CONCEPTS_PAGE_CLANS_CHAPTER_PLAYEROPS_PARA_3',		'BRIBING a clan: spend [ICON_GOLD] Gold to expel clan units from your territory and prevent them from targeting your cities for a set number of turns. Bribe costs start low but scale up the more cities you have. Clans that are bribed cannot be bribed again by the same player until the bribe expires, but they can be bribed by more than one player at a time. Bribing a clan increases their Free City conversion progress.'																																																																																	),
	(	'en_US',	'LOC_PEDIA_CONCEPTS_PAGE_CLANS_CHAPTER_PLAYEROPS_PARA_4',		'INCITING a clan: spend [ICON_GOLD] Gold to encourage the clan to raid and attack the cities of another civilization. You and the clan must share knowledge of at least one other civilization or City-State to be able to incite them. Incite costs are high, but the incitement has no expiration. However, clans can only be incited against one civilization at a time. Inciting a clan reduces its progress towards Free City conversion.'																																																																															),
	(	'en_US',	'LOC_PEDIA_CONCEPTS_PAGE_CLANS_CHAPTER_PLAYEROPS_PARA_5',		'RANSOMING a unit from a clan: if a clan has captured one of your civilian units, you can spend [ICON_GOLD] Gold to recover it. The cost to ransom a unit is always slightly less than the cost to purchase it new in one of your cities. Ransomed units appear the same turn at your closest City Center. Clans that ransom units lose progress towards Free City conversion.'																																																																																															),
	(	'en_US',	'LOC_PEDIA_CONCEPTS_PAGE_FREE_CITIES_1_CHAPTER_CONTENT_PARA_1',	'A Free City is a city formed out of a Barbarian Clan or a city which has left its original civilization due to a loss of Loyalty. These are not City-States, as they are likely to look towards rejoining one of the major civilizations of the game. A Free City has Loyalty to maintain just like a normal city, and accepts Loyalty pressure from other Civilizations. If its Loyalty reaches 0, it will join the Civilization that has exerted the most Loyalty pressure on it since the Free City became independent. This means there is a race against other civilizations when looking to attract a Free City into your civilization. Maximizing your Loyalty pressure will raise the chances that you will accumulate the most Loyalty and gain the city. '	);
